# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.98.0"

default_platform :ios

platform :ios do
  before_all do
    clear_derived_data
    cocoapods
  end

  desc "Build TSStaging, publish to fabric and notify on slack"
  lane :sandbox_scan do
    scan(
      workspace: "ios_sandbox.xcworkspace",
      scheme: "ios_sandbox",
      clean: true,
      output_directory: "fastlane/output/scan",
      output_types: "json-compilation-database",
      use_clang_report_name: true
    )
  end
  
  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end
end
